### PR TITLE
So many changes.

### PR DESCRIPTION
**Pull request by sellout**
in the build:
- update the copyright
- get rid of `CustomKeys`
- turn on `-Xlint`
- add separate scalacheck and tests projects

in the project:
- add `generalizeM`, `attribute` to AlgebraOps
- add tons of docs (which break with simulacrum)
- rename [co]alg params to `φ` and `ψ` consistently
- add a generalized apomorphism (`gapo`)
- add `ElgotAlgebraMOps`
- remove our custom `ownOps` because the bug is fixed in simulacrum
- separate distributive algebras into their own package
- generalize `ElgotAlgebra` over any comonad
- remove `ElgotCoalgebra` (its generalized form is identical to `CoalgebraM`)
- get rid of a few other unused functions (`holes`, `builder`)
- implement Arbitrary for all our types
- pull the example `Exp` and its algebras into their own files
- rename cofCata to elgotCata and added CofreeOps for it
- added elgotAna as its dual
- moved refolds to their own package to avoid namespace clutter
- moved Exp to its own package in the tests
- Move algebra operations into their own package (this includes adding
  “non-injected” `generalize` operations. And adds new `attributeAna`[†]
  folds (with a Kleisli, but not generalized, variant).
- delete unused `project` (not the one in `Recursive`)
- Clean up implicit names.
- add `generalizeElgotAlgebraM`
- add conversions between [co]algebras and transformations

Also adds documentation as well as (temporarily) commenting out the
documentation that breaks scaladoc for whatever reason.

[†]: courtesy @tpolecat

### CODE REVIEW

**Comment by sellout** [comment]
Moving this to “in progress” until I fix the coverage issues.

**Comment by wemrysi** [comment]
@sellout What's the status of this PR, I've been ignoring it since you changed it back to "in progress", just wanted to make sure you weren't waiting on me for something.

**Comment by sellout** [comment]
Unassigned! I think this PR will go away, and become like a dozen smaller PRs. I’ve already needed to borrow bits of it, and it’s just a mess anyway.

**Comment by wemrysi** [comment]
Right on, sounds good.

**Pull request closed without merging**
