### PR TITLE
add envTCobind

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by sellout** [comment]
Cool, thanks.

Could you add a `CHANGELOG/minor.md` file (and squash it into the existing commit), containing something like `- added CoBind[EnvT] with reduced constraint on the F type parameter`?

Other than that, looks ready to merge.

**Comment by xuwei-k** [comment]
done

**Comment by sellout** [comment]
Sorry for the delay. I actually meant making a _new_ file with the literal name `CHANGELOG/minor.md`. We have a script that manages incrementing the version properly based on that name, and renaming that file to the version, before publishing a new release.

I need to add contributor guidelines describing this stuff (and also open to lower-friction ways of handling our continuous semver stuff).

**Comment by sellout** [comment]
Thanks! Sorry it took so long to get merged.

**Pull request closed without merging**
