### PR TITLE
Add a documentation page about recursion schemes

### PR DESCRIPTION
**Pull request by vil1**

### CODE REVIEW

**Comment by jdegoes** [comment]
@vil1 Thank you. Looks great. 😄

**Comment by vil1** [comment]
Cool, expect some more on my next FLOSS day (Jan 24th).
At some point it would be nice if someone with the required credential could publish the microsite on github pages.

**Comment by jdegoes** [comment]
@vil1 I can do that. What are the involved steps?

**Comment by vil1** [comment]
You should first [initialize the gh-pages branch](https://github.com/sbt/sbt-ghpages/blob/7e2ee06180a5a955a89659915ec8cd75ea28147e/README.md#initializing-the-gh-pages-branch)
Then simply run the `publishMicrosite` task in sbt.
There's also an option to automatically publish via travis described [here](https://47deg.github.io/sbt-microsites/docs/publish-with-travis.html) (it's slightly more involved though)

**Pull request merged**
